### ISSUE TITLE
Uncovered content

### ISSUE THREAD

**Issue by pshriwise** [UW-Madison-ACI/2017-06-28-uwmadison-swc#5]
I'm thinking of removing the link to "Using Git in Rstudio" as I won't be covering this, but are these typically left in the workshop website in case people are curious?

Realistically I don't think it will do any harm, but there's the potential for some to find this link and get confused or wonder why we didn't cover that lesson.

**Comment by lmichael107** [comment]
If you say something during the workshop (we usually do) about it being a pointer, it can be good to leave it in so that people have a reference for later. -L

**Comment by pshriwise** [comment]
ok sounds good.
